export const city = [
  {
    title: "A",
    key: "A",
    items: [
      { id: 56, spell: "aba", name: "阿坝", cityCode: "5132" },
      { id: 57, spell: "akesu", name: "阿克苏", cityCode: "6529" },
      { id: 58, spell: "alashanmeng", name: "阿拉善盟", cityCode: "1529" },
      { id: 59, spell: "aletai", name: "阿勒泰", cityCode: "6543" },
      { id: 60, spell: "ali", name: "阿里", cityCode: "5425" },
      { id: 61, spell: "ankang", name: "安康", cityCode: "6109" },
      { id: 62, spell: "anqing", name: "安庆", cityCode: "3408" },
      { id: 63, spell: "anshan", name: "鞍山", cityCode: "2103" },
      { id: 64, spell: "anshun", name: "安顺", cityCode: "5204" },
      { id: 65, spell: "anyang", name: "安阳", cityCode: "4105" },
      { id: 338, spell: "acheng", name: "阿城", cityCode: "2301" },
      { id: 340, spell: "anji", name: "安吉", cityCode: "3305" },
      { id: 341, spell: "anning", name: "安宁", cityCode: "5301" },
      { id: 343, spell: "anxi", name: "安溪", cityCode: "3505" },
    ],
  },
  {
    title: "B",
    key: "B",
    items: [
      { id: 1, spell: "beijing", name: "北京", cityCode: "1101" },
      { id: 66, spell: "baicheng", name: "白城", cityCode: "2208" },
      { id: 67, spell: "baise", name: "百色", cityCode: "4510" },
      { id: 68, spell: "baishan", name: "白山", cityCode: "2206" },
      { id: 69, spell: "baiyin", name: "白银", cityCode: "6204" },
      { id: 70, spell: "bangbu", name: "蚌埠", cityCode: "3403" },
      { id: 71, spell: "baoding", name: "保定", cityCode: "1306" },
      { id: 72, spell: "baoji", name: "宝鸡", cityCode: "6103" },
      { id: 73, spell: "baoshan", name: "保山", cityCode: "5305" },
      { id: 74, spell: "baotou", name: "包头", cityCode: "1502" },
      { id: 75, spell: "bayannaoer", name: "巴彦淖尔", cityCode: "1508" },
      { id: 76, spell: "bayinguoleng", name: "巴音郭楞", cityCode: "6528" },
      { id: 77, spell: "bazhong", name: "巴中", cityCode: "5119" },
      { id: 78, spell: "beihai", name: "北海", cityCode: "4505" },
      { id: 79, spell: "benxi", name: "本溪", cityCode: "2105" },
      { id: 80, spell: "bijie", name: "毕节", cityCode: "5205" },
      { id: 81, spell: "binzhou", name: "滨州", cityCode: "3716" },
      { id: 82, spell: "boertala", name: "博尔塔拉", cityCode: "6527" },
      { id: 83, spell: "bozhou", name: "亳州", cityCode: "3416" },
      { id: 346, spell: "baoying", name: "宝应", cityCode: "3210" },
      { id: 348, spell: "binhai", name: "滨海", cityCode: "3209" },
      { id: 349, spell: "binxian", name: "宾县", cityCode: "2301" },
      { id: 351, spell: "bishan", name: "璧山", cityCode: "5001" },
      { id: 352, spell: "boai", name: "博爱", cityCode: "4108" },
      { id: 354, spell: "boxing", name: "博兴", cityCode: "3716" },
    ],
  },
  {
    title: "C",
    key: "C",
    items: [
      { id: 2, spell: "chongqing", name: "重庆", cityCode: "5000" },
      { id: 5, spell: "changchun", name: "长春", cityCode: "2201" },
      { id: 6, spell: "changsha", name: "长沙", cityCode: "4301" },
      { id: 7, spell: "changzhou", name: "常州", cityCode: "3204" },
      { id: 8, spell: "chengdu", name: "成都", cityCode: "5101" },
      { id: 84, spell: "cangzhou", name: "沧州", cityCode: "1309" },
      { id: 85, spell: "changde", name: "常德", cityCode: "4307" },
      { id: 86, spell: "changdu", name: "昌都", cityCode: "5403" },
      { id: 88, spell: "changzhi", name: "长治", cityCode: "1404" },
      { id: 89, spell: "chaohu", name: "巢湖", cityCode: "3401" },
      { id: 90, spell: "chaoyang", name: "朝阳", cityCode: "2113" },
      { id: 91, spell: "chaozhou", name: "潮州", cityCode: "4451" },
      { id: 92, spell: "chengde", name: "承德", cityCode: "1308" },
      { id: 93, spell: "chenzhou", name: "郴州", cityCode: "4310" },
      { id: 94, spell: "chifeng", name: "赤峰", cityCode: "1504" },
      { id: 95, spell: "chizhou", name: "池州", cityCode: "3417" },
      { id: 96, spell: "chongzuo", name: "崇左", cityCode: "4514" },
      { id: 97, spell: "chuxiong", name: "楚雄", cityCode: "5323" },
      { id: 98, spell: "chuzhou", name: "滁州", cityCode: "3411" },
      { id: 355, spell: "cangnan", name: "苍南", cityCode: "3303" },
      { id: 356, spell: "cangshan", name: "苍山", cityCode: "3706" },
      { id: 357, spell: "caoxian", name: "曹县", cityCode: "3717" },
      { id: 358, spell: "changdao", name: "长岛", cityCode: "3706" },
      { id: 361, spell: "changle", name: "长乐", cityCode: "3501" },
      { id: 362, spell: "changle", name: "昌乐", cityCode: "3707" },
      { id: 363, spell: "changshan", name: "常山", cityCode: "3308" },
      { id: 364, spell: "changshu", name: "常熟", cityCode: "3205" },
      { id: 366, spell: "changting", name: "长汀", cityCode: "3508" },
      { id: 367, spell: "changxing", name: "长兴", cityCode: "3305" },
      { id: 368, spell: "changyi", name: "昌邑", cityCode: "3707" },
      { id: 372, spell: "chengwu", name: "成武", cityCode: "3717" },
      { id: 374, spell: "chongren", name: "崇仁", cityCode: "3610" },
      { id: 375, spell: "chongyi", name: "崇义", cityCode: "3607" },
      { id: 376, spell: "chongzhou", name: "崇州", cityCode: "5101" },
      { id: 378, spell: "cixi", name: "慈溪", cityCode: "3302" },
      { id: 380, spell: "congyang", name: "枞阳", cityCode: "3407" },
    ],
  },
  {
    title: "D",
    key: "D",
    items: [
      { id: 9, spell: "dalian", name: "大连", cityCode: "2102" },
      { id: 10, spell: "dongguan", name: "东莞", cityCode: "4419" },
      { id: 99, spell: "dali", name: "大理", cityCode: "5329" },
      { id: 100, spell: "dandong", name: "丹东", cityCode: "2106" },
      { id: 101, spell: "daqing", name: "大庆", cityCode: "2306" },
      { id: 102, spell: "datong", name: "大同", cityCode: "1402" },
      { id: 103, spell: "daxinganling", name: "大兴安岭", cityCode: "2327" },
      { id: 104, spell: "dazhou", name: "达州", cityCode: "5117" },
      { id: 105, spell: "dehong", name: "德宏", cityCode: "5331" },
      { id: 106, spell: "deyang", name: "德阳", cityCode: "5106" },
      { id: 107, spell: "dezhou", name: "德州", cityCode: "3714" },
      { id: 108, spell: "dingxi", name: "定西", cityCode: "6211" },
      { id: 109, spell: "diqing", name: "迪庆", cityCode: "5334" },
      { id: 110, spell: "dongying", name: "东营", cityCode: "3705" },
      { id: 381, spell: "dafeng", name: "大丰", cityCode: "3209" },
      { id: 382, spell: "daishan", name: "岱山", cityCode: "3309" },
      { id: 383, spell: "dangshan", name: "砀山", cityCode: "3413" },
      { id: 385, spell: "danxian", name: "单县", cityCode: "3717" },
      { id: 386, spell: "danyang", name: "丹阳", cityCode: "3211" },
      { id: 387, spell: "dapu", name: "大埔", cityCode: "4414" },
      { id: 388, spell: "datian", name: "大田", cityCode: "3504" },
      { id: 389, spell: "dayi", name: "大邑", cityCode: "5101" },
      { id: 392, spell: "dean", name: "德安", cityCode: "3604" },
      { id: 393, spell: "dehua", name: "德化", cityCode: "3505" },
      { id: 394, spell: "dehui", name: "德惠", cityCode: "2201" },
      { id: 396, spell: "deqing", name: "德清", cityCode: "3305" },
      { id: 397, spell: "deqing", name: "德庆", cityCode: "4412" },
      { id: 398, spell: "dexing", name: "德兴", cityCode: "3611" },
      { id: 399, spell: "dianbai", name: "电白", cityCode: "4409" },
      { id: 403, spell: "dingyuan", name: "定远", cityCode: "3411" },
      { id: 404, spell: "donga", name: "东阿", cityCode: "3715" },
      { id: 405, spell: "donghai", name: "东海", cityCode: "3207" },
      { id: 407, spell: "dongping", name: "东平", cityCode: "3709" },
      { id: 408, spell: "dongshan", name: "东山", cityCode: "3506" },
      { id: 409, spell: "dongtai", name: "东台", cityCode: "3209" },
      { id: 410, spell: "dongtou", name: "洞头", cityCode: "3303" },
      { id: 411, spell: "dongxiang", name: "东乡", cityCode: "3610" },
      { id: 412, spell: "dongyang", name: "东阳", cityCode: "3307" },
      { id: 413, spell: "dongyuan", name: "东源", cityCode: "4416" },
      { id: 416, spell: "dujiangyan", name: "都江堰", cityCode: "5101" },
    ],
  },
  {
    title: "E",
    key: "E",
    items: [
      { id: 111, spell: "eerduosi", name: "鄂尔多斯", cityCode: "1506" },
      { id: 112, spell: "enshi", name: "恩施", cityCode: "4228" },
      { id: 113, spell: "ezhou", name: "鄂州", cityCode: "4207" },
      { id: 417, spell: "enping", name: "恩平", cityCode: "4407" },
    ],
  },
  {
    title: "F",
    key: "F",
    items: [
      { id: 11, spell: "foshan", name: "佛山", cityCode: "4406" },
      { id: 12, spell: "fuzhou", name: "福州", cityCode: "3501" },
      { id: 114, spell: "fangchenggang", name: "防城港", cityCode: "4506" },
      { id: 115, spell: "fushun", name: "抚顺", cityCode: "2104" },
      { id: 116, spell: "fuxin", name: "阜新", cityCode: "2109" },
      { id: 117, spell: "fuyang", name: "阜阳", cityCode: "3412" },
      { id: 118, spell: "fuzhou", name: "抚州", cityCode: "3610" },
      { id: 420, spell: "fangzheng", name: "方正", cityCode: "2301" },
      { id: 422, spell: "feidong", name: "肥东", cityCode: "3401" },
      { id: 424, spell: "feixian", name: "费县", cityCode: "3713" },
      { id: 425, spell: "fengcheng", name: "丰城", cityCode: "3609" },
      { id: 426, spell: "fengdu", name: "丰都", cityCode: "5002" },
      { id: 427, spell: "fenghua", name: "奉化", cityCode: "3302" },
      { id: 428, spell: "fengjie", name: "奉节", cityCode: "5002" },
      { id: 432, spell: "fengxian", name: "丰县", cityCode: "3203" },
      { id: 433, spell: "fengxin", name: "奉新", cityCode: "3609" },
      { id: 434, spell: "fengyang", name: "凤阳", cityCode: "3411" },
      { id: 435, spell: "fenyi", name: "分宜", cityCode: "3605" },
      { id: 437, spell: "fuan", name: "福安", cityCode: "3509" },
      { id: 442, spell: "funing", name: "阜宁", cityCode: "3209" },
      { id: 443, spell: "fuqing", name: "福清", cityCode: "3501" },
    ],
  },
  {
    title: "G",
    key: "G",
    items: [
      { id: 13, spell: "guangzhou", name: "广州", cityCode: "4401" },
      { id: 14, spell: "guiyang", name: "贵阳", cityCode: "5201" },
      { id: 119, spell: "gannan", name: "甘南", cityCode: "6230" },
      { id: 120, spell: "ganzhou", name: "赣州", cityCode: "3607" },
      { id: 122, spell: "guangan", name: "广安", cityCode: "5116" },
      { id: 123, spell: "guangyuan", name: "广元", cityCode: "5108" },
      { id: 124, spell: "guigang", name: "贵港", cityCode: "4508" },
      { id: 125, spell: "guilin", name: "桂林", cityCode: "4503" },
      { id: 126, spell: "guoluo", name: "果洛", cityCode: "6326" },
      { id: 127, spell: "guyuan", name: "固原", cityCode: "6404" },
      { id: 445, spell: "ganxian", name: "赣县", cityCode: "3607" },
      { id: 446, spell: "ganyu", name: "赣榆", cityCode: "3207" },
      { id: 447, spell: "gaoan", name: "高安", cityCode: "3609" },
      { id: 451, spell: "gaoling", name: "高陵", cityCode: "6101" },
      { id: 454, spell: "gaotang", name: "高唐", cityCode: "3715" },
      { id: 457, spell: "gaoyou", name: "高邮", cityCode: "3210" },
      { id: 459, spell: "gongyi", name: "巩义", cityCode: "4101" },
      { id: 461, spell: "guangde", name: "广德", cityCode: "3418" },
      { id: 463, spell: "guangning", name: "广宁", cityCode: "4412" },
      { id: 464, spell: "guangrao", name: "广饶", cityCode: "3705" },
      { id: 467, spell: "guanxian", name: "冠县", cityCode: "3715" },
      { id: 470, spell: "gutian", name: "古田", cityCode: "3509" },
    ],
  },
  {
    title: "H",
    key: "H",
    items: [
      { id: 15, spell: "haerbin", name: "哈尔滨", cityCode: "2301" },
      { id: 16, spell: "haikou", name: "海口", cityCode: "4601" },
      { id: 17, spell: "handan", name: "邯郸", cityCode: "1304" },
      { id: 18, spell: "hangzhou", name: "杭州", cityCode: "3301" },
      { id: 19, spell: "hefei", name: "合肥", cityCode: "3401" },
      { id: 20, spell: "huizhou", name: "惠州", cityCode: "4413" },
      { id: 129, spell: "haidong", name: "海东", cityCode: "6302" },
      { id: 130, spell: "hainan", name: "海南", cityCode: "4600" },
      { id: 131, spell: "haixi", name: "海西", cityCode: "6328" },
      { id: 132, spell: "hami", name: "哈密", cityCode: "6505" },
      { id: 133, spell: "hanzhong", name: "汉中", cityCode: "6107" },
      { id: 134, spell: "hebi", name: "鹤壁", cityCode: "4106" },
      { id: 135, spell: "hechi", name: "河池", cityCode: "4512" },
      { id: 136, spell: "hegang", name: "鹤岗", cityCode: "2304" },
      { id: 137, spell: "heihe", name: "黑河", cityCode: "2311" },
      { id: 138, spell: "hengshui", name: "衡水", cityCode: "1311" },
      { id: 139, spell: "hengyang", name: "衡阳", cityCode: "4304" },
      { id: 140, spell: "hetiandi", name: "和田地", cityCode: "6532" },
      { id: 141, spell: "heyuan", name: "河源", cityCode: "4416" },
      { id: 142, spell: "heze", name: "菏泽", cityCode: "3717" },
      { id: 143, spell: "hezhou", name: "贺州", cityCode: "4511" },
      { id: 145, spell: "huaian", name: "淮安", cityCode: "3208" },
      { id: 146, spell: "huaibei", name: "淮北", cityCode: "3406" },
      { id: 147, spell: "huaihua", name: "怀化", cityCode: "4312" },
      { id: 148, spell: "huainan", name: "淮南", cityCode: "3404" },
      { id: 149, spell: "huanggang", name: "黄冈", cityCode: "4211" },
      { id: 151, spell: "huangshan", name: "黄山", cityCode: "3410" },
      { id: 152, spell: "huangshi", name: "黄石", cityCode: "4202" },
      { id: 153, spell: "huhehaote", name: "呼和浩特", cityCode: "1501" },
      { id: 154, spell: "huludao", name: "葫芦岛", cityCode: "2114" },
      { id: 155, spell: "hulunbeier", name: "呼伦贝尔", cityCode: "1507" },
      { id: 156, spell: "huzhou", name: "湖州", cityCode: "3305" },
      { id: 472, spell: "haian", name: "海安", cityCode: "3206" },
      { id: 473, spell: "haifeng", name: "海丰", cityCode: "4415" },
      { id: 474, spell: "haimen", name: "海门", cityCode: "3206" },
      { id: 475, spell: "haining", name: "海宁", cityCode: "3304" },
      { id: 476, spell: "haiyan", name: "海盐", cityCode: "3304" },
      { id: 477, spell: "haiyang", name: "海阳", cityCode: "3706" },
      { id: 481, spell: "hengxian", name: "横县", cityCode: "4501" },
      { id: 483, spell: "heshan", name: "鹤山", cityCode: "4407" },
      { id: 484, spell: "hexian", name: "和县", cityCode: "3405" },
      { id: 485, spell: "hongze", name: "洪泽", cityCode: "3208" },
      { id: 486, spell: "huaan", name: "华安", cityCode: "3506" },
      { id: 490, spell: "huaiyuan", name: "怀远", cityCode: "3403" },
      { id: 493, spell: "huian", name: "惠安", cityCode: "3505" },
      { id: 495, spell: "huidong", name: "惠东", cityCode: "4413" },
      { id: 498, spell: "hukou", name: "湖口", cityCode: "3604" },
      { id: 499, spell: "hulan", name: "呼兰", cityCode: "2301" },
      { id: 500, spell: "huoqiu", name: "霍邱", cityCode: "3415" },
      { id: 501, spell: "huoshan", name: "霍山", cityCode: "3415" },
      { id: 502, spell: "huxian", name: "户县", cityCode: "6101" },
    ],
  },
  {
    title: "J",
    key: "J",
    items: [
      { id: 21, spell: "jiaozuo", name: "焦作", cityCode: "4108" },
      { id: 22, spell: "jiaxing", name: "嘉兴", cityCode: "3304" },
      { id: 23, spell: "jilin", name: "吉林", cityCode: "2200" },
      { id: 24, spell: "jinan", name: "济南", cityCode: "3701" },
      { id: 157, spell: "jiamusi", name: "佳木斯", cityCode: "2308" },
      { id: 158, spell: "jiangmen", name: "江门", cityCode: "4407" },
      { id: 159, spell: "jian", name: "吉安", cityCode: "3608" },
      { id: 160, spell: "jiayuguan", name: "嘉峪关", cityCode: "6202" },
      { id: 161, spell: "jieyang", name: "揭阳", cityCode: "4452" },
      { id: 162, spell: "jinchang", name: "金昌", cityCode: "6203" },
      { id: 163, spell: "jincheng", name: "晋城", cityCode: "1405" },
      { id: 164, spell: "jingdezhen", name: "景德镇", cityCode: "3602" },
      { id: 165, spell: "jingmen", name: "荆门", cityCode: "4208" },
      { id: 166, spell: "jingzhou", name: "荆州", cityCode: "4210" },
      { id: 167, spell: "jinhua", name: "金华", cityCode: "3307" },
      { id: 168, spell: "jining", name: "济宁", cityCode: "3708" },
      { id: 169, spell: "jinzhong", name: "晋中", cityCode: "1407" },
      { id: 170, spell: "jinzhou", name: "锦州", cityCode: "2107" },
      { id: 171, spell: "jiujiang", name: "九江", cityCode: "3604" },
      { id: 172, spell: "jiuquan", name: "酒泉", cityCode: "6209" },
      { id: 173, spell: "jixi", name: "鸡西", cityCode: "2303" },
      { id: 505, spell: "jiangjin", name: "江津", cityCode: "5001" },
      { id: 507, spell: "jiangshan", name: "江山", cityCode: "3308" },
      { id: 508, spell: "jiangyan", name: "姜堰", cityCode: "3212" },
      { id: 509, spell: "jiangyin", name: "江阴", cityCode: "3202" },
      { id: 511, spell: "jianning", name: "建宁", cityCode: "3504" },
      { id: 512, spell: "jianou", name: "建瓯", cityCode: "3507" },
      { id: 513, spell: "jianyang", name: "建阳", cityCode: "3507" },
      { id: 514, spell: "jian", name: "吉安", cityCode: "3608" },
      { id: 515, spell: "jiaohe", name: "蛟河", cityCode: "2202" },
      { id: 516, spell: "jiaoling", name: "蕉岭", cityCode: "4414" },
      { id: 517, spell: "jiaonan", name: "胶南", cityCode: "3702" },
      { id: 519, spell: "jiashan", name: "嘉善", cityCode: "3304" },
      { id: 520, spell: "jiaxiang", name: "嘉祥", cityCode: "3708" },
      { id: 524, spell: "jimo", name: "即墨", cityCode: "3702" },
      { id: 526, spell: "jingde", name: "旌德", cityCode: "3418" },
      { id: 527, spell: "jinggangshan", name: "井冈山", cityCode: "3608" },
      { id: 528, spell: "jingjiang", name: "靖江", cityCode: "3212" },
      { id: 530, spell: "jingxian", name: "泾县", cityCode: "3418" },
      { id: 531, spell: "jingxing", name: "井陉", cityCode: "1301" },
      { id: 532, spell: "jinhu", name: "金湖", cityCode: "3208" },
      { id: 533, spell: "jinjiang", name: "晋江", cityCode: "3505" },
      { id: 534, spell: "jinmen", name: "金门", cityCode: "3505" },
      { id: 535, spell: "jinning", name: "晋宁", cityCode: "5301" },
      { id: 537, spell: "jintang", name: "金堂", cityCode: "5101" },
      { id: 540, spell: "jinxiang", name: "金乡", cityCode: "3708" },
      { id: 542, spell: "jinzhai", name: "金寨", cityCode: "3415" },
      { id: 543, spell: "jinzhou", name: "晋州", cityCode: "1301" },
      { id: 545, spell: "jiujiang", name: "九江", cityCode: "3604" },
      { id: 546, spell: "jiutai", name: "九台", cityCode: "2201" },
      { id: 548, spell: "jiyang", name: "济阳", cityCode: "3701" },
      { id: 549, spell: "jiyuan", name: "济源", cityCode: "4190" },
      { id: 552, spell: "jurong", name: "句容", cityCode: "3211" },
      { id: 553, spell: "juxian", name: "莒县", cityCode: "3711" },
    ],
  },
  {
    title: "K",
    key: "K",
    items: [
      { id: 25, spell: "kunming", name: "昆明", cityCode: "5301" },
      { id: 174, spell: "kaifeng", name: "开封", cityCode: "4102" },
      { id: 175, spell: "kashidi", name: "喀什地", cityCode: "6531" },
      { id: 176, spell: "kelamayi", name: "克拉玛依", cityCode: "6502" },
      { id: 177, spell: "kezile", name: "克孜勒", cityCode: "6530" },
      { id: 555, spell: "kaihua", name: "开化", cityCode: "3308" },
      { id: 556, spell: "kaiping", name: "开平", cityCode: "4407" },
      { id: 557, spell: "kaixian", name: "开县", cityCode: "5001" },
      { id: 561, spell: "kunshan", name: "昆山", cityCode: "3205" },
    ],
  },
  {
    title: "L",
    key: "L",
    items: [
      { id: 26, spell: "lanzhou", name: "兰州", cityCode: "6201" },
      { id: 27, spell: "liuzhou", name: "柳州", cityCode: "4502" },
      { id: 28, spell: "luoyang", name: "洛阳", cityCode: "4103" },
      { id: 178, spell: "laibin", name: "来宾", cityCode: "4513" },
      { id: 179, spell: "laiwu", name: "莱芜", cityCode: "3701" },
      { id: 180, spell: "langfang", name: "廊坊", cityCode: "1310" },
      { id: 181, spell: "lasa", name: "拉萨", cityCode: "5401" },
      { id: 182, spell: "leshan", name: "乐山", cityCode: "5111" },
      { id: 183, spell: "liangshan", name: "凉山", cityCode: "5134" },
      { id: 184, spell: "lianyungang", name: "连云港", cityCode: "3207" },
      { id: 185, spell: "liaocheng", name: "聊城", cityCode: "3715" },
      { id: 186, spell: "liaoyang", name: "辽阳", cityCode: "2110" },
      { id: 187, spell: "liaoyuan", name: "辽源", cityCode: "2204" },
      { id: 188, spell: "lijiang", name: "丽江", cityCode: "5307" },
      { id: 189, spell: "lincang", name: "临沧", cityCode: "5309" },
      { id: 190, spell: "linfen", name: "临汾", cityCode: "1410" },
      { id: 191, spell: "linxia", name: "临夏", cityCode: "6229" },
      { id: 192, spell: "linyi", name: "临沂", cityCode: "3713" },
      { id: 193, spell: "linzhi", name: "林芝", cityCode: "5404" },
      { id: 194, spell: "lishui", name: "丽水", cityCode: "3311" },
      { id: 195, spell: "liuan", name: "六安", cityCode: "3415" },
      { id: 196, spell: "liupanshui", name: "六盘水", cityCode: "5202" },
      { id: 197, spell: "longnan", name: "陇南", cityCode: "6212" },
      { id: 198, spell: "longyan", name: "龙岩", cityCode: "3508" },
      { id: 199, spell: "loudi", name: "娄底", cityCode: "4313" },
      { id: 200, spell: "luohe", name: "漯河", cityCode: "4111" },
      { id: 201, spell: "luzhou", name: "泸州", cityCode: "5105" },
      { id: 202, spell: "lvliang", name: "吕梁", cityCode: "1411" },
      { id: 565, spell: "laizhou", name: "莱州", cityCode: "3706" },
      { id: 567, spell: "lantian", name: "蓝田", cityCode: "6101" },
      { id: 568, spell: "lanxi", name: "兰溪", cityCode: "3307" },
      { id: 569, spell: "lean", name: "乐安", cityCode: "3610" },
      { id: 570, spell: "lechang", name: "乐昌", cityCode: "4402" },
      { id: 571, spell: "leizhou", name: "雷州", cityCode: "4408" },
      { id: 574, spell: "leqing", name: "乐清", cityCode: "3303" },
      { id: 575, spell: "leting", name: "乐亭", cityCode: "1302" },
      { id: 578, spell: "liangshan", name: "梁山", cityCode: "3708" },
      { id: 579, spell: "lianhua", name: "莲花", cityCode: "3603" },
      { id: 580, spell: "lianjiang", name: "连江", cityCode: "3501" },
      { id: 582, spell: "liannan", name: "连南", cityCode: "4418" },
      { id: 584, spell: "lianshan", name: "连山", cityCode: "4418" },
      { id: 585, spell: "lianshui", name: "涟水", cityCode: "3208" },
      { id: 586, spell: "lianzhou", name: "连州", cityCode: "4418" },
      { id: 587, spell: "liaozhong", name: "辽中", cityCode: "2101" },
      { id: 589, spell: "lijin", name: "利津", cityCode: "3705" },
      { id: 592, spell: "lingshou", name: "灵寿", cityCode: "1301" },
      { id: 594, spell: "linhai", name: "临海", cityCode: "3310" },
      { id: 596, spell: "linquan", name: "临泉", cityCode: "3412" },
      { id: 597, spell: "linqu", name: "临朐", cityCode: "3707" },
      { id: 598, spell: "linshu", name: "临沭", cityCode: "3713" },
      { id: 599, spell: "linyi", name: "临邑", cityCode: "3714" },
      { id: 600, spell: "lishui", name: "溧水", cityCode: "3201" },
      { id: 601, spell: "liucheng", name: "柳城", cityCode: "4502" },
      { id: 602, spell: "liujiang", name: "柳江", cityCode: "4502" },
      { id: 607, spell: "longchuan", name: "龙川", cityCode: "4416" },
      { id: 608, spell: "longhai", name: "龙海", cityCode: "3506" },
      { id: 609, spell: "longkou", name: "龙口", cityCode: "3706" },
      { id: 610, spell: "longmen", name: "龙门", cityCode: "4413" },
      { id: 611, spell: "longnan", name: "龙南", cityCode: "3607" },
      { id: 612, spell: "longquan", name: "龙泉", cityCode: "3311" },
      { id: 613, spell: "longyou", name: "龙游", cityCode: "3308" },
      { id: 614, spell: "luancheng", name: "栾城", cityCode: "1301" },
      { id: 615, spell: "luanchuan", name: "栾川", cityCode: "4103" },
      { id: 617, spell: "luanxian", name: "滦县", cityCode: "1302" },
      { id: 624, spell: "luquan", name: "鹿泉", cityCode: "1301" },
      { id: 627, spell: "luzhai", name: "鹿寨", cityCode: "4502" },
    ],
  },
  {
    title: "M",
    key: "M",
    items: [
      { id: 203, spell: "maanshan", name: "马鞍山", cityCode: "3405" },
      { id: 204, spell: "maoming", name: "茂名", cityCode: "4409" },
      { id: 205, spell: "meishan", name: "眉山", cityCode: "5114" },
      { id: 206, spell: "meizhou", name: "梅州", cityCode: "4414" },
      { id: 207, spell: "mianyang", name: "绵阳", cityCode: "5107" },
      { id: 208, spell: "mudanjiang", name: "牡丹江", cityCode: "2310" },
      { id: 628, spell: "mashan", name: "马山", cityCode: "4501" },
      { id: 629, spell: "meixian", name: "梅县", cityCode: "4414" },
      { id: 630, spell: "mengcheng", name: "蒙城", cityCode: "3416" },
      { id: 632, spell: "mengyin", name: "蒙阴", cityCode: "3713" },
      { id: 633, spell: "mengzhou", name: "孟州", cityCode: "4108" },
      { id: 636, spell: "minhou", name: "闽侯", cityCode: "3501" },
      { id: 638, spell: "mulan", name: "木兰", cityCode: "2301" },
    ],
  },
  {
    title: "N",
    key: "N",
    items: [
      { id: 29, spell: "nanchang", name: "南昌", cityCode: "3601" },
      { id: 30, spell: "nanjing", name: "南京", cityCode: "3201" },
      { id: 31, spell: "nanning", name: "南宁", cityCode: "4501" },
      { id: 32, spell: "nantong", name: "南通", cityCode: "3206" },
      { id: 33, spell: "ningbo", name: "宁波", cityCode: "3302" },
      { id: 209, spell: "nanchong", name: "南充", cityCode: "5113" },
      { id: 210, spell: "nanping", name: "南平", cityCode: "3507" },
      { id: 211, spell: "nanyang", name: "南阳", cityCode: "4113" },
      { id: 212, spell: "naqu", name: "那曲", cityCode: "5406" },
      { id: 213, spell: "neijiang", name: "内江", cityCode: "5110" },
      { id: 214, spell: "ningde", name: "宁德", cityCode: "3509" },
      { id: 215, spell: "nujiang", name: "怒江", cityCode: "5333" },
      { id: 639, spell: "nanan", name: "南安", cityCode: "3505" },
      { id: 640, spell: "nanao", name: "南澳", cityCode: "4405" },
      { id: 642, spell: "nanchuan", name: "南川", cityCode: "5001" },
      { id: 645, spell: "nankang", name: "南康", cityCode: "3607" },
      { id: 646, spell: "nanling", name: "南陵", cityCode: "3402" },
      { id: 647, spell: "nanxiong", name: "南雄", cityCode: "4402" },
      { id: 650, spell: "ninghai", name: "宁海", cityCode: "3302" },
      { id: 653, spell: "ningxiang", name: "宁乡", cityCode: "4301" },
      { id: 654, spell: "ningyang", name: "宁阳", cityCode: "3709" },
      { id: 655, spell: "nongan", name: "农安", cityCode: "2201" },
    ],
  },
  {
    title: "P",
    key: "P",
    items: [
      { id: 216, spell: "panjin", name: "盘锦", cityCode: "2111" },
      { id: 217, spell: "panzhihua", name: "攀枝花", cityCode: "5104" },
      { id: 218, spell: "pingdingshan", name: "平顶山", cityCode: "4104" },
      { id: 219, spell: "pingliang", name: "平凉", cityCode: "6208" },
      { id: 220, spell: "pingxiang", name: "萍乡", cityCode: "3603" },
      { id: 221, spell: "puer", name: "普洱", cityCode: "5308" },
      { id: 222, spell: "putian", name: "莆田", cityCode: "3503" },
      { id: 223, spell: "puyang", name: "濮阳", cityCode: "4109" },
      { id: 656, spell: "panan", name: "磐安", cityCode: "3307" },
      { id: 658, spell: "peixian", name: "沛县", cityCode: "3203" },
      { id: 659, spell: "penglai", name: "蓬莱", cityCode: "3706" },
      { id: 663, spell: "pingdu", name: "平度", cityCode: "3702" },
      { id: 664, spell: "pinghe", name: "平和", cityCode: "3506" },
      { id: 665, spell: "pinghu", name: "平湖", cityCode: "3304" },
      { id: 666, spell: "pingnan", name: "屏南", cityCode: "3509" },
      { id: 667, spell: "pingshan", name: "平山", cityCode: "1301" },
      { id: 668, spell: "pingtan", name: "平潭", cityCode: "3501" },
      { id: 669, spell: "pingyang", name: "平阳", cityCode: "3303" },
      { id: 670, spell: "pingyin", name: "平阴", cityCode: "3701" },
      { id: 673, spell: "pingyuan", name: "平远", cityCode: "4414" },
      { id: 674, spell: "pixian", name: "郫县", cityCode: "5101" },
      { id: 676, spell: "poyang", name: "鄱阳", cityCode: "3611" },
      { id: 678, spell: "pujiang", name: "浦江", cityCode: "3307" },
      { id: 680, spell: "pulandian", name: "普兰店", cityCode: "2102" },
    ],
  },
  {
    title: "Q",
    key: "Q",
    items: [
      { id: 34, spell: "qingdao", name: "青岛", cityCode: "3702" },
      { id: 35, spell: "quanzhou", name: "泉州", cityCode: "3505" },
      { id: 227, spell: "qingyang", name: "庆阳", cityCode: "6210" },
      { id: 228, spell: "qingyuan", name: "清远", cityCode: "4418" },
      { id: 229, spell: "qinhuangdao", name: "秦皇岛", cityCode: "1303" },
      { id: 230, spell: "qinzhou", name: "钦州", cityCode: "4507" },
      { id: 231, spell: "qiqihaer", name: "齐齐哈尔", cityCode: "2302" },
      { id: 232, spell: "qitaihe", name: "七台河", cityCode: "2309" },
      { id: 233, spell: "qujing", name: "曲靖", cityCode: "5303" },
      { id: 234, spell: "quzhou", name: "衢州", cityCode: "3308" },
      { id: 683, spell: "qianshan", name: "潜山", cityCode: "3408" },
      { id: 686, spell: "qidong", name: "启东", cityCode: "3206" },
      { id: 688, spell: "qijiang", name: "綦江", cityCode: "5001" },
      { id: 689, spell: "qimen", name: "祁门", cityCode: "3410" },
      { id: 690, spell: "qingliu", name: "清流", cityCode: "3504" },
      { id: 692, spell: "qingxin", name: "清新", cityCode: "4418" },
      { id: 693, spell: "qingyang", name: "青阳", cityCode: "3417" },
      { id: 694, spell: "qingyuan", name: "庆元", cityCode: "3311" },
      { id: 696, spell: "qingzhen", name: "清镇", cityCode: "5201" },
      { id: 697, spell: "qingzhou", name: "青州", cityCode: "3707" },
      { id: 699, spell: "qionglai", name: "邛崃", cityCode: "5101" },
      { id: 703, spell: "qufu", name: "曲阜", cityCode: "3708" },
    ],
  },
  {
    title: "R",
    key: "R",
    items: [
      { id: 235, spell: "rikaze", name: "日喀则", cityCode: "5402" },
      { id: 236, spell: "rizhao", name: "日照", cityCode: "3711" },
      { id: 706, spell: "renhua", name: "仁化", cityCode: "4402" },
      { id: 709, spell: "rongcheng", name: "荣成", cityCode: "3710" },
      { id: 710, spell: "rongshui", name: "融水", cityCode: "4502" },
      { id: 711, spell: "rudong", name: "如东", cityCode: "3206" },
      { id: 713, spell: "ruian", name: "瑞安", cityCode: "3303" },
      { id: 716, spell: "rushan", name: "乳山", cityCode: "3710" },
    ],
  },
  {
    title: "S",
    key: "S",
    items: [
      { id: 3, spell: "shanghai", name: "上海", cityCode: "3100" },
      { id: 36, spell: "shenyang", name: "沈阳", cityCode: "2101" },
      { id: 37, spell: "shenzhen", name: "深圳", cityCode: "4403" },
      { id: 38, spell: "shijiazhuang", name: "石家庄", cityCode: "1301" },
      { id: 39, spell: "suzhou", name: "苏州", cityCode: "3205" },
      { id: 237, spell: "sanmenxia", name: "三门峡", cityCode: "4112" },
      { id: 238, spell: "sanming", name: "三明", cityCode: "3504" },
      { id: 239, spell: "sanya", name: "三亚", cityCode: "4602" },
      { id: 240, spell: "shangluo", name: "商洛", cityCode: "6110" },
      { id: 241, spell: "shangqiu", name: "商丘", cityCode: "4114" },
      { id: 242, spell: "shangrao", name: "上饶", cityCode: "3611" },
      { id: 243, spell: "shannan", name: "山南", cityCode: "5405" },
      { id: 244, spell: "shantou", name: "汕头", cityCode: "4405" },
      { id: 245, spell: "shanwei", name: "汕尾", cityCode: "4415" },
      { id: 246, spell: "shaoguan", name: "韶关", cityCode: "4402" },
      { id: 247, spell: "shaoxing", name: "绍兴", cityCode: "3306" },
      { id: 248, spell: "shaoyang", name: "邵阳", cityCode: "4305" },
      { id: 249, spell: "shiyan", name: "十堰", cityCode: "4203" },
      { id: 250, spell: "shizuishan", name: "石嘴山", cityCode: "6402" },
      { id: 251, spell: "shuangyashan", name: "双鸭山", cityCode: "2305" },
      { id: 252, spell: "shuozhou", name: "朔州", cityCode: "1406" },
      { id: 253, spell: "siping", name: "四平", cityCode: "2203" },
      { id: 254, spell: "songyuan", name: "松原", cityCode: "2207" },
      { id: 255, spell: "suihua", name: "绥化", cityCode: "2312" },
      { id: 256, spell: "suining", name: "遂宁", cityCode: "5109" },
      { id: 257, spell: "suizhou", name: "随州", cityCode: "4213" },
      { id: 258, spell: "suqian", name: "宿迁", cityCode: "3213" },
      { id: 259, spell: "suzhou", name: "宿州", cityCode: "3413" },
      { id: 719, spell: "sanjiang", name: "三江", cityCode: "4502" },
      { id: 722, spell: "shanggao", name: "上高", cityCode: "3609" },
      { id: 723, spell: "shanghang", name: "上杭", cityCode: "3508" },
      { id: 724, spell: "shanghe", name: "商河", cityCode: "3701" },
      { id: 726, spell: "shanglin", name: "上林", cityCode: "4501" },
      { id: 727, spell: "shangrao", name: "上饶", cityCode: "3611" },
      { id: 729, spell: "shangyu", name: "上虞", cityCode: "3306" },
      { id: 730, spell: "shangzhi", name: "尚志", cityCode: "2301" },
      { id: 731, spell: "shaowu", name: "邵武", cityCode: "3507" },
      { id: 732, spell: "shaoxing", name: "绍兴", cityCode: "3306" },
      { id: 733, spell: "shaxian", name: "沙县", cityCode: "3504" },
      { id: 734, spell: "shengsi", name: "嵊泗", cityCode: "3309" },
      { id: 736, spell: "shenxian", name: "莘县", cityCode: "3715" },
      { id: 738, spell: "shexian", name: "歙县", cityCode: "3410" },
      { id: 740, spell: "shicheng", name: "石城", cityCode: "3607" },
      { id: 741, spell: "shilin", name: "石林", cityCode: "5301" },
      { id: 742, spell: "shishi", name: "石狮", cityCode: "3505" },
      { id: 743, spell: "shitai", name: "石台", cityCode: "3417" },
      { id: 745, spell: "shizhu", name: "石柱", cityCode: "5002" },
      { id: 748, spell: "shouxian", name: "寿县", cityCode: "3404" },
      { id: 749, spell: "shuangcheng", name: "双城", cityCode: "2301" },
      { id: 750, spell: "shuangliu", name: "双流", cityCode: "5101" },
      { id: 751, spell: "shucheng", name: "舒城", cityCode: "3415" },
      { id: 757, spell: "sishui", name: "泗水", cityCode: "3708" },
      { id: 758, spell: "sixian", name: "泗县", cityCode: "3413" },
      { id: 759, spell: "siyang", name: "泗阳", cityCode: "3213" },
      { id: 761, spell: "songxi", name: "松溪", cityCode: "3507" },
      { id: 762, spell: "songxian", name: "嵩县", cityCode: "4103" },
      { id: 764, spell: "suichang", name: "遂昌", cityCode: "3311" },
      { id: 768, spell: "suixi", name: "遂溪", cityCode: "4408" },
    ],
  },
  {
    title: "T",
    key: "T",
    items: [
      { id: 4, spell: "tianjin", name: "天津", cityCode: "1200" },
      { id: 40, spell: "taizhou", name: "台州", cityCode: "3310" },
      { id: 41, spell: "tangshan", name: "唐山", cityCode: "1302" },
      { id: 260, spell: "tachengdi", name: "塔城地", cityCode: "6542" },
      { id: 261, spell: "taian", name: "泰安", cityCode: "3709" },
      { id: 262, spell: "taiyuan", name: "太原", cityCode: "1401" },
      { id: 263, spell: "taizhou", name: "泰州", cityCode: "3212" },
      { id: 264, spell: "tianshui", name: "天水", cityCode: "6205" },
      { id: 265, spell: "tieling", name: "铁岭", cityCode: "2112" },
      { id: 266, spell: "tongchuan", name: "铜川", cityCode: "6102" },
      { id: 267, spell: "tonghua", name: "通化", cityCode: "2205" },
      { id: 268, spell: "tongliao", name: "通辽", cityCode: "1505" },
      { id: 269, spell: "tongling", name: "铜陵", cityCode: "3407" },
      { id: 270, spell: "tongren", name: "铜仁", cityCode: "5206" },
      { id: 271, spell: "tulufan", name: "吐鲁番", cityCode: "6504" },
      { id: 771, spell: "taicang", name: "太仓", cityCode: "3205" },
      { id: 772, spell: "taihe", name: "太和", cityCode: "3412" },
      { id: 774, spell: "taihu", name: "太湖", cityCode: "3408" },
      { id: 775, spell: "taining", name: "泰宁", cityCode: "3504" },
      { id: 776, spell: "taishan", name: "台山", cityCode: "4407" },
      { id: 777, spell: "taishun", name: "泰顺", cityCode: "3303" },
      { id: 778, spell: "taixing", name: "泰兴", cityCode: "3212" },
      { id: 779, spell: "tancheng", name: "郯城", cityCode: "3713" },
      { id: 780, spell: "tanghai", name: "唐海", cityCode: "1302" },
      { id: 782, spell: "tianchang", name: "天长", cityCode: "3411" },
      { id: 783, spell: "tiantai", name: "天台", cityCode: "3310" },
      { id: 784, spell: "tongcheng", name: "桐城", cityCode: "3408" },
      { id: 785, spell: "tonggu", name: "铜鼓", cityCode: "3609" },
      { id: 788, spell: "tongling", name: "铜陵", cityCode: "3407" },
      { id: 791, spell: "tongshan", name: "铜山", cityCode: "3203" },
      { id: 792, spell: "tongxiang", name: "桐乡", cityCode: "3304" },
      { id: 793, spell: "tongzhou", name: "通州", cityCode: "3206" },
    ],
  },
  {
    title: "W",
    key: "W",
    items: [
      { id: 42, spell: "weifang", name: "潍坊", cityCode: "3707" },
      { id: 43, spell: "weihai", name: "威海", cityCode: "3710" },
      { id: 44, spell: "wuhan", name: "武汉", cityCode: "4201" },
      { id: 45, spell: "wuxi", name: "无锡", cityCode: "3202" },
      { id: 272, spell: "weinan", name: "渭南", cityCode: "6105" },
      { id: 274, spell: "wenzhou", name: "温州", cityCode: "3303" },
      { id: 275, spell: "wuhai", name: "乌海", cityCode: "1503" },
      { id: 276, spell: "wuhu", name: "芜湖", cityCode: "3402" },
      { id: 277, spell: "wulanchabu", name: "乌兰察布", cityCode: "1509" },
      { id: 278, spell: "wulumuqi", name: "乌鲁木齐", cityCode: "6501" },
      { id: 279, spell: "wuwei", name: "武威", cityCode: "6206" },
      { id: 280, spell: "wuzhong", name: "吴忠", cityCode: "6403" },
      { id: 281, spell: "wuzhou", name: "梧州", cityCode: "4504" },
      { id: 794, spell: "wafangdian", name: "瓦房店", cityCode: "2102" },
      { id: 796, spell: "wangcheng", name: "望城", cityCode: "4301" },
      { id: 798, spell: "wannian", name: "万年", cityCode: "3611" },
      { id: 799, spell: "wanzai", name: "万载", cityCode: "3609" },
      { id: 801, spell: "wencheng", name: "文成", cityCode: "3303" },
      { id: 802, spell: "wendeng", name: "文登", cityCode: "3710" },
      { id: 804, spell: "wenling", name: "温岭", cityCode: "3310" },
      { id: 805, spell: "wenshang", name: "汶上", cityCode: "3708" },
      { id: 806, spell: "wenxian", name: "温县", cityCode: "4108" },
      { id: 808, spell: "wuchang", name: "五常", cityCode: "2301" },
      { id: 809, spell: "wucheng", name: "武城", cityCode: "3714" },
      { id: 813, spell: "wuhu", name: "芜湖", cityCode: "3402" },
      { id: 816, spell: "wujiang", name: "吴江", cityCode: "3205" },
      { id: 820, spell: "wuning", name: "武宁", cityCode: "3604" },
      { id: 822, spell: "wushan", name: "巫山", cityCode: "5002" },
      { id: 826, spell: "wuyishan", name: "武夷山", cityCode: "3507" },
      { id: 827, spell: "wuyuan", name: "婺源", cityCode: "3611" },
    ],
  },
  {
    title: "X",
    key: "X",
    items: [
      { id: 46, spell: "xiamen", name: "厦门", cityCode: "3502" },
      { id: 47, spell: "xian", name: "西安", cityCode: "6101" },
      { id: 48, spell: "xuchang", name: "许昌", cityCode: "4110" },
      { id: 49, spell: "xuzhou", name: "徐州", cityCode: "3203" },
      { id: 283, spell: "xiangtan", name: "湘潭", cityCode: "4303" },
      { id: 284, spell: "xiangxi", name: "湘西", cityCode: "4331" },
      { id: 285, spell: "xianning", name: "咸宁", cityCode: "4212" },
      { id: 286, spell: "xianyang", name: "咸阳", cityCode: "6104" },
      { id: 287, spell: "xiaogan", name: "孝感", cityCode: "4209" },
      {
        id: 288,
        spell: "xilinguolemeng",
        name: "锡林郭勒盟",
        cityCode: "1525",
      },
      { id: 289, spell: "xinganmeng", name: "兴安盟", cityCode: "1522" },
      { id: 290, spell: "xingtai", name: "邢台", cityCode: "1305" },
      { id: 291, spell: "xining", name: "西宁", cityCode: "6301" },
      { id: 292, spell: "xinxiang", name: "新乡", cityCode: "4107" },
      { id: 293, spell: "xinyang", name: "信阳", cityCode: "4115" },
      { id: 294, spell: "xinyu", name: "新余", cityCode: "3605" },
      { id: 295, spell: "xinzhou", name: "忻州", cityCode: "1409" },
      { id: 296, spell: "xishuangbanna", name: "西双版纳", cityCode: "5328" },
      { id: 297, spell: "xuancheng", name: "宣城", cityCode: "3418" },
      { id: 831, spell: "xiangshan", name: "象山", cityCode: "3302" },
      { id: 832, spell: "xiangshui", name: "响水", cityCode: "3209" },
      { id: 833, spell: "xianju", name: "仙居", cityCode: "3310" },
      { id: 834, spell: "xianyou", name: "仙游", cityCode: "3503" },
      { id: 835, spell: "xiaoxian", name: "萧县", cityCode: "3413" },
      { id: 836, spell: "xiapu", name: "霞浦", cityCode: "3509" },
      { id: 838, spell: "xinan", name: "新安", cityCode: "4103" },
      { id: 839, spell: "xinchang", name: "新昌", cityCode: "3306" },
      { id: 840, spell: "xinfeng", name: "信丰", cityCode: "3607" },
      { id: 841, spell: "xinfeng", name: "新丰", cityCode: "4402" },
      { id: 843, spell: "xingguo", name: "兴国", cityCode: "3607" },
      { id: 844, spell: "xinghua", name: "兴化", cityCode: "3212" },
      { id: 845, spell: "xingning", name: "兴宁", cityCode: "4414" },
      { id: 848, spell: "xingzi", name: "星子", cityCode: "3604" },
      { id: 849, spell: "xinji", name: "辛集", cityCode: "1301" },
      { id: 850, spell: "xinjian", name: "新建", cityCode: "3601" },
      { id: 851, spell: "xinjin", name: "新津", cityCode: "5101" },
      { id: 853, spell: "xinmin", name: "新民", cityCode: "2101" },
      { id: 858, spell: "xinyi", name: "信宜", cityCode: "4409" },
      { id: 859, spell: "xinzheng", name: "新郑", cityCode: "4101" },
      { id: 860, spell: "xiuning", name: "休宁", cityCode: "3410" },
      { id: 861, spell: "xiushan", name: "秀山", cityCode: "5001" },
      { id: 862, spell: "xiushui", name: "修水", cityCode: "3604" },
      { id: 863, spell: "xiuwen", name: "修文", cityCode: "5201" },
      { id: 868, spell: "xuyi", name: "盱眙", cityCode: "3208" },
    ],
  },
  {
    title: "Y",
    key: "Y",
    items: [
      { id: 50, spell: "yangzhou", name: "扬州", cityCode: "3210" },
      { id: 51, spell: "yantai", name: "烟台", cityCode: "3706" },
      { id: 298, spell: "yaan", name: "雅安", cityCode: "5118" },
      { id: 299, spell: "yanan", name: "延安", cityCode: "6106" },
      { id: 300, spell: "yanbian", name: "延边", cityCode: "2224" },
      { id: 301, spell: "yancheng", name: "盐城", cityCode: "3209" },
      { id: 302, spell: "yangjiang", name: "阳江", cityCode: "4417" },
      { id: 303, spell: "yangquan", name: "阳泉", cityCode: "1403" },
      { id: 304, spell: "yibin", name: "宜宾", cityCode: "5115" },
      { id: 305, spell: "yichang", name: "宜昌", cityCode: "4205" },
      { id: 306, spell: "yichun", name: "伊春", cityCode: "2307" },
      { id: 307, spell: "yichun", name: "宜春", cityCode: "3609" },
      { id: 309, spell: "yinchuan", name: "银川", cityCode: "6401" },
      { id: 310, spell: "yingkou", name: "营口", cityCode: "2108" },
      { id: 311, spell: "yingtan", name: "鹰潭", cityCode: "3606" },
      { id: 312, spell: "yiyang", name: "益阳", cityCode: "4309" },
      { id: 313, spell: "yongzhou", name: "永州", cityCode: "4311" },
      { id: 314, spell: "yueyang", name: "岳阳", cityCode: "4306" },
      { id: 315, spell: "yulin", name: "玉林", cityCode: "4509" },
      { id: 316, spell: "yulin", name: "榆林", cityCode: "6108" },
      { id: 317, spell: "yuncheng", name: "运城", cityCode: "1408" },
      { id: 318, spell: "yunfu", name: "云浮", cityCode: "4453" },
      { id: 319, spell: "yushu", name: "玉树", cityCode: "6327" },
      { id: 320, spell: "yuxi", name: "玉溪", cityCode: "5304" },
      { id: 869, spell: "yangchun", name: "阳春", cityCode: "4417" },
      { id: 871, spell: "yanggu", name: "阳谷", cityCode: "3715" },
      { id: 872, spell: "yangshan", name: "阳山", cityCode: "4418" },
      { id: 882, spell: "yilan", name: "依兰", cityCode: "2301" },
      { id: 885, spell: "yingde", name: "英德", cityCode: "4418" },
      { id: 887, spell: "yishui", name: "沂水", cityCode: "3713" },
      { id: 888, spell: "yiwu", name: "义乌", cityCode: "3307" },
      { id: 889, spell: "yixian", name: "黟县", cityCode: "3410" },
      { id: 890, spell: "yixing", name: "宜兴", cityCode: "3202" },
      { id: 892, spell: "yiyang", name: "宜阳", cityCode: "4103" },
      { id: 895, spell: "yongan", name: "永安", cityCode: "3504" },
      { id: 897, spell: "yongchun", name: "永春", cityCode: "3505" },
      { id: 901, spell: "yongji", name: "永吉", cityCode: "2202" },
      { id: 902, spell: "yongjia", name: "永嘉", cityCode: "3303" },
      { id: 903, spell: "yongkang", name: "永康", cityCode: "3307" },
      { id: 905, spell: "yongtai", name: "永泰", cityCode: "3501" },
      { id: 907, spell: "yongxiu", name: "永修", cityCode: "3604" },
      { id: 908, spell: "youxi", name: "尤溪", cityCode: "3504" },
      { id: 909, spell: "youyang", name: "酉阳", cityCode: "5002" },
      { id: 911, spell: "yucheng", name: "禹城", cityCode: "3714" },
      { id: 912, spell: "yudu", name: "于都", cityCode: "3607" },
      { id: 914, spell: "yugan", name: "余干", cityCode: "3611" },
      { id: 916, spell: "yujiang", name: "余江", cityCode: "3606" },
      { id: 919, spell: "yuncheng", name: "郓城", cityCode: "3717" },
      { id: 920, spell: "yunhe", name: "云和", cityCode: "3311" },
      { id: 922, spell: "yunyang", name: "云阳", cityCode: "5002" },
      { id: 923, spell: "yushan", name: "玉山", cityCode: "3611" },
      { id: 924, spell: "yushu", name: "榆树", cityCode: "2201" },
      { id: 926, spell: "yutian", name: "玉田", cityCode: "1302" },
      { id: 927, spell: "yuyao", name: "余姚", cityCode: "3302" },
    ],
  },
  {
    title: "Z",
    key: "Z",
    items: [
      { id: 52, spell: "zhangzhou", name: "漳州", cityCode: "3506" },
      { id: 53, spell: "zhengzhou", name: "郑州", cityCode: "4101" },
      { id: 54, spell: "zhongshan", name: "中山", cityCode: "4420" },
      { id: 55, spell: "zhuhai", name: "珠海", cityCode: "4404" },
      { id: 321, spell: "zaozhuang", name: "枣庄", cityCode: "3704" },
      { id: 322, spell: "zhangjiajie", name: "张家界", cityCode: "4308" },
      { id: 323, spell: "zhangjiakou", name: "张家口", cityCode: "1307" },
      { id: 324, spell: "zhangye", name: "张掖", cityCode: "6207" },
      { id: 325, spell: "zhanjiang", name: "湛江", cityCode: "4408" },
      { id: 326, spell: "zhaoqing", name: "肇庆", cityCode: "4412" },
      { id: 327, spell: "zhaotong", name: "昭通", cityCode: "5306" },
      { id: 328, spell: "zhenjiang", name: "镇江", cityCode: "3211" },
      { id: 329, spell: "zhongwei", name: "中卫", cityCode: "6405" },
      { id: 330, spell: "zhoukou", name: "周口", cityCode: "4116" },
      { id: 331, spell: "zhoushan", name: "舟山", cityCode: "3309" },
      { id: 332, spell: "zhumadian", name: "驻马店", cityCode: "4117" },
      { id: 333, spell: "zhuzhou", name: "株洲", cityCode: "4302" },
      { id: 334, spell: "zibo", name: "淄博", cityCode: "3703" },
      { id: 335, spell: "zigong", name: "自贡", cityCode: "5103" },
      { id: 336, spell: "ziyang", name: "资阳", cityCode: "5120" },
      { id: 337, spell: "zunyi", name: "遵义", cityCode: "5203" },
      { id: 930, spell: "zengcheng", name: "增城", cityCode: "4401" },
      { id: 931, spell: "zhangjiagang", name: "张家港", cityCode: "3205" },
      { id: 932, spell: "zhangping", name: "漳平", cityCode: "3508" },
      { id: 933, spell: "zhangpu", name: "漳浦", cityCode: "3506" },
      { id: 934, spell: "zhangqiu", name: "章丘", cityCode: "3701" },
      { id: 935, spell: "zhangshu", name: "樟树", cityCode: "3609" },
      { id: 936, spell: "zhanhua", name: "沾化", cityCode: "3716" },
      { id: 937, spell: "zhaoxian", name: "赵县", cityCode: "1301" },
      { id: 939, spell: "zhengding", name: "正定", cityCode: "1301" },
      { id: 940, spell: "zhenghe", name: "政和", cityCode: "3507" },
      { id: 943, spell: "zhongxian", name: "忠县", cityCode: "5002" },
      { id: 946, spell: "zhuanghe", name: "庄河", cityCode: "2102" },
      { id: 947, spell: "zhucheng", name: "诸城", cityCode: "3707" },
      { id: 948, spell: "zhuji", name: "诸暨", cityCode: "3306" },
      { id: 949, spell: "zijin", name: "紫金", cityCode: "4416" },
      { id: 951, spell: "zoucheng", name: "邹城", cityCode: "3708" },
      { id: 952, spell: "zouping", name: "邹平", cityCode: "3716" },
      { id: 953, spell: "zunhua", name: "遵化", cityCode: "1302" },
    ],
  },
];
